### PR TITLE
Adjust scalar type aliases to make build pass on Windows

### PR DESCRIPTION
**Pull request by nordlow**

### CODE REVIEW

**Comment by emil-perhinschi** [comment]
thank you

tested the pull in linux and there were no problems, don't have windows right now to check though

**Comment by nordlow** [comment]
> thank you
> 
> tested the pull in linux and there were no problems, don't have windows right now to check though

Great! Can you create a new minor tag and sync code.dlang.org?

**Comment by emil-perhinschi** [comment]
done 

building on windows probably deserves 0.2.0 

made you admin on github

is there a way to give ownership or co-ownership on code.dlang.org ?

**Comment by nordlow** [comment]
> building on windows probably deserves 0.2.0

Linking on windows requires provisioning libzip (zip.lib) which I have found suprisingly difficult to do.

> made you admin

Thank you.

> is there a way to give ownership or co-ownership on code.dlang.org ?

I don't know.

**Pull request merged**
